export const START_FETCHING_PRODUCTS = 'redux/talents/START_FETCHING_PRODUCTS';
export const SUCCESS_FETCHING_PRODUCTS = 'redux/talents/SUCCESS_FETCHING_PRODUCTS';
export const ERROR_FETCHING_PRODUCTS = 'redux/talents/ERROR_FETCHING_PRODUCTS';
export const SET_KEYWORD = 'redux/talents/SET_KEYWORD';